### ISSUE TITLE
[Bug] ⪆ `versionName=4.5.0` of `ch.protonmail.android` `FATAL EXCEPTION`s with “`IllegalArgumentException`: Key "9" was already used” when accessing or scrolling in folders containing ⪆ 15 conversations.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [ProtonMail/protoncore_android#27]
#### Cause / Reproduction

Invoke the application.

#### Crash

1. #### Dump / Trace

   <blockquote>

   ~~~YAML
   FATAL EXCEPTION: main
   Process: ch.protonmail.android, PID: 7057
   java.lang.IllegalArgumentException: Key "9" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
   	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(Unknown Source:154)
   	at ch.protonmail.android.maillabel.presentation.ui.LabelsListKt$$ExternalSyntheticLambda0.invoke(Unknown Source:457)
   	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(Unknown Source:71)
   	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:37)
   	at androidx.compose.foundation.layout.WrapContentNode.measure-3p2s80s(Unknown Source:56)
   	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
   	at androidx.paging.PagingDataPresenter$1.invoke(Unknown Source:544)
   	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(Unknown Source:55)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:51)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:131)
   	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:130)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(Unknown Source:92)
   	at androidx.compose.foundation.layout.OffsetKt.measure(Unknown Source:94)
   	at androidx.compose.foundation.layout.RowMeasurePolicy.measure-3p2s80s(Unknown Source:45)
   	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:37)
   	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(Unknown Source:96)
   	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
   	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(Unknown Source:32)
   	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
   	at androidx.paging.PagingDataPresenter$1.invoke(Unknown Source:544)
   	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(Unknown Source:55)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:51)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:131)
   	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:130)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(Unknown Source:92)
   	at androidx.compose.foundation.layout.OffsetKt.measure(Unknown Source:94)
   	at androidx.compose.foundation.layout.ColumnMeasurePolicy.measure-3p2s80s(Unknown Source:45)
   	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:37)
   	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(Unknown Source:32)
   	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
   	at androidx.paging.PagingDataPresenter$1.invoke(Unknown Source:544)
   	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(Unknown Source:55)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:51)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:131)
   	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:130)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(Unknown Source:92)
   	at androidx.compose.foundation.layout.OffsetKt.measure(Unknown Source:94)
   	at androidx.compose.foundation.layout.RowMeasurePolicy.measure-3p2s80s(Unknown Source:45)
   	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:37)
   	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(Unknown Source:96)
   	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
   	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(Unknown Source:32)
   	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
   	at androidx.paging.PagingDataPresenter$1.invoke(Unknown Source:544)
   	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(Unknown Source:55)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:51)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:131)
   	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:130)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(Unknown Source:92)
   	at androidx.compose.foundation.layout.OffsetKt.measure(Unknown Source:94)
   	at androidx.compose.foundation.layout.RowMeasurePolicy.measure-3p2s80s(Unknown Source:45)
   	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:37)
   	at androidx.compose.foundation.layout.OffsetPxNode.measure-3p2s80s(Unknown Source:0)
   	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
   	at androidx.paging.PagingDataPresenter$1.invoke(Unknown Source:544)
   	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(Unknown Source:55)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:51)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:131)
   	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:130)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(Unknown Source:92)
   	at androidx.compose.foundation.layout.BoxMeasurePolicy.measure-3p2s80s(Unknown Source:256)
   	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:37)
   	at androidx.paging.PagingDataPresenter$1.invoke(Unknown Source:544)
   	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(Unknown Source:55)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:51)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:131)
   	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:130)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(Unknown Source:92)
   	at androidx.compose.foundation.layout.BoxMeasurePolicy.measure-3p2s80s(Unknown Source:84)
   	at androidx.paging.HintHandler$forceSetHint$2.invoke(Unknown Source:2006)
   	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(Unknown Source:71)
   	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:37)
   	at androidx.paging.PagingDataPresenter$1.invoke(Unknown Source:544)
   	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(Unknown Source:55)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:51)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:131)
   	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:130)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(Unknown Source:92)
   	at androidx.compose.foundation.layout.BoxMeasurePolicy.measure-3p2s80s(Unknown Source:84)
   	at androidx.paging.HintHandler$forceSetHint$2.invoke(Unknown Source:2006)
   	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(Unknown Source:71)
   	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:37)
   	at androidx.paging.PagingDataPresenter$1.invoke(Unknown Source:544)
   	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(Unknown Source:55)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:51)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:131)
   	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:130)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(Unknown Source:92)
   	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(Unknown Source:55)
   	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1$measuredItemProvider$1.getAndMeasure-0kLqBqw(Unknown Source:20)
   	at androidx.compose.material3.CardKt$Card$4.invoke(Unknown Source:878)
   	at androidx.paging.HintHandler$forceSetHint$2.invoke(Unknown Source:1814)
   	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(Unknown Source:71)
   	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:37)
   	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(Unknown Source:0)
   	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
   	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(Unknown Source:96)
   	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
   	at androidx.paging.PagingDataPresenter$1.invoke(Unknown Source:544)
   	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(Unknown Source:55)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:51)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:131)
   	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:130)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(Unknown Source:92)
   	at androidx.compose.foundation.layout.BoxMeasurePolicy.measure-3p2s80s(Unknown Source:256)
   	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:37)
   	at androidx.compose.foundation.layout.PaddingValuesModifier.measure-3p2s80s(Unknown Source:114)
   	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
   	at androidx.paging.PagingDataPresenter$1.invoke(Unknown Source:544)
   	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(Unknown Source:113)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:51)
   	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:131)
   	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
   	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:130)
   	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(Unknown Source:16)
   	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(Unknown Source:17)
   	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(Unknown Source:7)
   	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(Unknown Source:117)
   	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(Unknown Source:93)
   	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(Unknown Source:35)
   	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:14)
   	at android.view.View.draw(View.java:23901)
   	at android.view.View.updateDisplayListIfDirty(View.java:22765)
   	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
   	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
   	at android.view.View.updateDisplayListIfDirty(View.java:22721)
   	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
   	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
   	at android.view.View.updateDisplayListIfDirty(View.java:22721)
   	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
   	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
   	at android.view.View.updateDisplayListIfDirty(View.java:22721)
   	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
   	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
   	at android.view.View.updateDisplayListIfDirty(View.java:22721)
   	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
   	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
   	at android.view.View.updateDisplayListIfDirty(View.java:22721)
   	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
   	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
   	at android.view.View.updateDisplayListIfDirty(View.java:22721)
   	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
   	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
   	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
   	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4957)
   	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4661)
   	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3840)
   	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2483)
   	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9332)
   	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1425)
   	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1434)
   	at android.view.Choreographer.doCallbacks(Choreographer.java:1037)
   	at android.view.Choreographer.doFrame(Choreographer.java:965)
   	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1408)
   	at android.os.Handler.handleCallback(Handler.java:958)
   	at android.os.Handler.dispatchMessage(Handler.java:99)
   	at android.os.Looper.loopOnce(Looper.java:205)
   	at android.os.Looper.loop(Looper.java:294)
   	at android.app.ActivityThread.main(ActivityThread.java:8223)
   	at java.lang.reflect.Method.invoke(Native Method)
   	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)

   ~~~

   </blockquote>

1. #### Acquisition

   Acquired via [`f-droid.org/repo/taco.scoop_34.apk`](https://f-droid.org/repo/taco.scoop_34.apk) with [`github.com/TacoTheDank/Scoop/wiki/Home#instructions-for-non-rooted-users`](https://github.com/TacoTheDank/Scoop/wiki/Home/76df7b439fa92c4da115615de9515fd0eaec819e#instructions-for-non-rooted-users:~:text=adb%20shell%20pm%20grant%20taco.scoop%20android.permission.READ_LOGS) enabled.

#### Environment

1. #### Application

   1. ~~~sh
      #!/usr/bin/env sh
      adb shell dumpsys package 'ch.protonmail.android' | grep -e 'versionName'
      ~~~

   1. <blockquote>

      ~~~ini
      versionName=4.5.0
      ~~~

      </blockquote>

   It's from [`play.google.com/store/apps/details?id=ch.protonmail.android&hl=en_GB`](https://play.google.com/store/apps/details?id=ch.protonmail.android&hl=en_GB#:~:text=Icon%20image-,Proton%20Mail,-:%20Encrypted%20Email).

1. #### Device

   [Fairphone 5](https://www.wikidata.org/w/index.php?title=Q122070914&oldid=2278534168#Statements:~:text=Random%20Lexeme-,Fairphone%205,-(Q122070914))

1. #### OS

   > ~~~YAML
   > [ro.build.display.id]: [FP5.UT2H.B.088.20241122]
   > ~~~

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ProtonMail/protoncore_android/issues/27#issue-2756278593

@ProtonMail, I want to report it via https://proton.me/support/troubleshooting?product=mail, but your presets are significantly too basic and specific.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ProtonMail/protoncore_android/issues/27#issue-2756278593

To my knowledge, this occurred not after an application update, but after I added YAML-style colons to my labels (to remediate Proton Mail's lack of GMail-like tag hierarchy):

![screenshot-mail proton me-2024 12 23-17_13_08](https://github.com/user-attachments/assets/3b3b87dd-a2d2-4358-8251-32faa28d1fdb)

I can't verify this though, because they might have occurred simultaneously.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ProtonMail/protoncore_android/issues/27#issuecomment-2560052368

It appears to function now. How strange.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ProtonMail/protoncore_android/issues/27#event-15768420520

Considering that there was no update between the time the crash occurred and fixed itself, and now I've hit https://github.com/ProtonMail/protoncore_android/issues/27#ref-issue-2789620385, I'm going to reopen this for official triage.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/ProtonMail/protoncore_android/issues/27#issuecomment-2592571182

I was naive to think that https://github.com/ProtonMail/protoncore_android/issues/27#issuecomment-2592571182 might occur. I'd like to again close this in favour of https://github.com/ProtonMail/protoncore_android/issues/29#issuecomment-2607041427 because the SEGFAULT reason is identical, and the cause that I presumed does appear to correlate with it, but I don't know whether to close it as completed or as a duplicate. Please triage.
